[package]
name = "ender_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
# serde_json = "1.0"
# serde = { version = "1.0", features = ["derive"] }
walkdir = "2"
rayon = "1.7"


[lib]
crate-type = ["cdylib"]
